# Generated by Django 3.2.6 on 2021-08-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '__first__'),
        ('udhari_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Bill', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('belongs_to_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_creator', to='udhari_user.udhariuser')),
            ],
        ),
        migrations.CreateModel(
            name='BillContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('amount_contributed', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('belongs_to_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udhari_user.udhariuser')),
            ],
        ),
    ]
