# Generated by Django 3.1.6 on 2021-05-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udhari_user', '0001_initial'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_creator', to='udhari_user.udhariuser'),
        ),
        migrations.AlterField(
            model_name='billcontributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udhari_user.udhariuser'),
        ),
    ]
