# Generated by Django 3.2.6 on 2021-08-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_billcontributor_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcontributor',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
