# Generated by Django 3.2.6 on 2021-09-07 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_alter_billcontributor_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcontributor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2021, 9, 8)),
            preserve_default=False,
        ),
    ]
