# Generated by Django 3.2.6 on 2021-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_billcontributor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
