# Generated by Django 3.2.6 on 2021-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_alter_bill_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcontributor',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
