# Generated by Django 3.2.6 on 2021-09-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_alter_billcontributor_share'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billcontributor',
            index=models.Index(fields=['user'], name='bill_billco_user_id_aea77e_idx'),
        ),
    ]
