# Generated by Django 3.2.6 on 2021-09-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_billcontributor_bill_billco_user_id_aea77e_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billcontributor',
            name='bill_billco_user_id_aea77e_idx',
        ),
    ]
