# Generated by Django 3.2.6 on 2021-09-07 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_remove_billcontributor_bill_billco_user_id_aea77e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2021, 9, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billcontributor',
            name='amount_contributed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
