# Generated by Django 3.2.6 on 2021-09-07 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_auto_20210908_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcontributor',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2021, 9, 8)),
            preserve_default=False,
        ),
    ]
