# Generated by Django 3.2.6 on 2021-09-07 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_billcontributor_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 43, 6, 291522, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='billcontributor',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 20, 43, 6, 292154, tzinfo=utc)),
        ),
    ]
