# Generated by Django 3.2.6 on 2021-09-07 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_auto_20210908_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billcontributor',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
