# Generated by Django 3.2.6 on 2021-09-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_auto_20210908_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcontributor',
            name='belongs_to_bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bill.bill'),
            preserve_default=False,
        ),
    ]
