# Generated by Django 3.1.6 on 2021-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UdhariUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11)),
                ('country_code', models.CharField(default='+91', max_length=4)),
                ('photo_url', models.URLField(default='https://i.stack.imgur.com/l60Hf.png')),
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('auth_token', models.CharField(max_length=64)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
