# Generated by Django 3.1.6 on 2021-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UdhariUser',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=11)),
                ('country_code', models.CharField(default='+91', max_length=4)),
                ('photo_url', models.URLField()),
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
