# Generated by Django 3.2.6 on 2021-08-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udhari_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udhariuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
