# Generated by Django 3.2.6 on 2021-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udhari_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udhariuser',
            name='auth_token',
        ),
    ]
