# Generated by Django 3.1.6 on 2021-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20210321_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
