# Generated by Django 3.1.6 on 2021-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_remove_trip_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
