# Generated by Django 3.1.6 on 2021-03-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_trip_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
    ]
