# Generated by Django 3.1.6 on 2021-03-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
    ]
