# Generated by Django 3.1.6 on 2021-03-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('trip', '0006_remove_trip_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(default=917743960763, on_delete=django.db.models.deletion.CASCADE, related_name='trip_creator', to='user.user'),
            preserve_default=False,
        ),
    ]
