# Generated by Django 3.1.6 on 2021-03-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_trip_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bills_id_array',
        ),
    ]
