# Generated by Django 3.1.6 on 2021-03-21 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_remove_trip_bills_id_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bills_id_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
