# Generated by Django 3.1.6 on 2021-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('photo_url', models.URLField()),
                ('uid', models.CharField(max_length=30)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
