# Generated by Django 3.1.6 on 2021-05-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('udhari_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udhari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isDone', models.BooleanField(default=False)),
                ('isMerged', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udhari_borrower', to='udhari_user.udhariuser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udhari_creator', to='udhari_user.udhariuser')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udhari_sender', to='udhari_user.udhariuser')),
            ],
        ),
    ]
